### ISSUE TITLE
Update to the recent 9.0.1 release, and also provide beta channel with 10.0.0 version

### ISSUE THREAD

**Issue by bam80** [flathub/io.qt.QtCreator#108]
The published 8.0.1 version is outdated already, and unreleased yet 10 version contains a new useful feature, so it would be very attractive to have it on beta channel to give it an early try:
https://bugreports.qt.io/browse/QTCREATORBUG-28138

Currently, I don't see the beta flatpak channel at all.

**Comment by marbub** [comment]
It is now on 13.0.2.
