### ISSUE TITLE
Cannot open project in Qt Creator latest Flatpak version

### ISSUE THREAD

**Issue by jesse-tong** [flathub/io.qt.QtCreator#148]
When I open Qt Creator installed by Flathub at the latest version as of today (2023/09/10), there's an output when starting it through terminal:
`QIBusPlatformInputContext: invalid portal bus. Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed`

When I tried to open any project from Qt Creator, the first time the terminal output a warning:
`atk-bridge: get_device_events_reply: unknown signature` 
Then Qt Creator freezes for a while and there's no popup to open a project.

Additional information:
-Distro: EndeavourOS
-Kernel version: 6.1.52-1-lts
-Flatpak repos: In the attachment.
-App permission: Default permissions for Qt Creator on Flathub (cannot show to output now because I uninstalled Qt Creator and use native version now).

Attachments:
[flatpak_remote.txt](https://github.com/flathub/io.qt.QtCreator/files/12567836/flatpak_remote.txt)
[flatpak_runtime.txt](https://github.com/flathub/io.qt.QtCreator/files/12567837/flatpak_runtime.txt)

**Comment by marbub** [comment]
Do you still experience that problem with the new release?
