### ISSUE TITLE
'Command not found' for tools used by make

### ISSUE THREAD

**Issue by karadoc** [flathub/io.qt.QtCreator#149]
I have a project for which the makefile runs `protoc`. This works if I just type `make` into a terminal; but if I try to build from QtCreator it tells me 

> /bin/sh: line 1: protoc: command not found

The location of protoc is /usr/bin/protoc. And I've confirmed that /usr/bin is listed in the path of build environment. So I'd expect it to findable. However, I notice that when I manually 'append path' in QtCreator and select /usr/bin, the path it actually appends is `/run/user/1000/doc/4bf63b5/bin`. After doing this, protoc does get found when make is invoked by QtCreator, but I get different error:

> protoc: error while loading shared libraries: libprotoc.so.23: cannot open shared object file: No such file or directory

To me these problems look like they are caused by some flatpak sandbox / permissions weirdness that I don't understand.

**Comment by marbub** [comment]
It is using the /usr from the run time. Accessing the /usr from outside the sandbox has to be supported upstream in Qt Creator.

**Comment by karadoc** [comment]
I don't fully understand what you mean. When `make` is launched by the non-flatpak version of Qt Creator, it can execute stuff from `/usr/bin`. So I don't know what changes that version would need in order to make it also work in the flatpak version. But in any case, it sounds like you're telling me that it isn't really fixable. I'm sorry to hear that, but I guess that's just bad luck for me.

**Comment by Erick555** [comment]
flatpak has its own `/usr/bin` separate from host system and the same on all hosts (that's why it can run on all hosts). Your system specific binaries aren't there. You can launch shell inside flatpak as `flatpak run --command=sh io.qt.QtCreator` then list `/usr/bin` content to see that.

**Comment by 4c0n** [comment]
It could perhaps be an option to have qt creator execute things in your os using the flatpak-spawn command. It is a bit complicated to set up and I'm not sure if qt creator is able to support that.
I have been doing that in other IDE's, so it's not impossible 😅

**Comment by karadoc** [comment]
> It could perhaps be an option to have qt creator execute things in your os using the flatpak-spawn command. It is a bit complicated to set up and I'm not sure if qt creator is able to support that. I have been doing that in other IDE's, so it's not impossible 😅

At first test, this looks like a good workaround. I don't know much about these things, so I've never heard of flatpak-spawn (and I don't know what D-Bus is). But I just enabled 'D-Bus session bus', and changed my QtCreator build command from `make` to `flatpak-spawn --host make`, and it seems to have worked properly. It found the required stuff to run and link against. So apparently that's a solution to my problem.  Many thanks for the idea! Needing to put `flatpak-spawn` in the command isn't perfect, but it's not a big deal once I know about it. And I think I do understand now why it would be difficult to fix the problem any other way.

Previously I'd assumed that if the flatpak was set to allow access to "all system files" etc. then it would just see all `/usr/bin` stuff as normal; but apparently things are a bit more complex than that.

In any case, I'm pleased to have good workaround. I'll test it over the next few days, but I don't expect any other problems.

**Comment by marbub** [comment]
flatpack-spawn --host can execute the executable outside of flatpack. But the paths you get back have to be marked too. QtCreator has already support for that. But in that case, we need to write a plugin. It should not be super complicated. But somebody has to write it.

**Comment by marbub** [comment]
I spoke with one of the Qt Creator developers. You can add an SSH server to your machine and then make a remote Linux connection inside of Qt Creator. It is not super fast, but it works.

If there is an extra plugin that uses flat-spawn --host and host-os, it would be much faster.

**Comment by 4c0n** [comment]
Hopefully someone will make one and maintain it then 😉

**Comment by marbub** [comment]
I could do it, but the use case is limited. You can use Conan or vcpkg to work around it. Remote Linux inside Qt Creator is an other workaround. Let's see.

**Comment by marbub** [comment]
I added Conan to the flatpak. Together with QtCreator: https://www.qt.io/blog/qt-creator-cmake-package-manager-auto-setup it should you provide with protobuf(https://conan.io/center/recipes/protobuf).
