### ISSUE TITLE
new version check seems not to work

### ISSUE THREAD

**Issue by marbub** [flathub/io.qt.QtCreator#165]

**Comment by marbub** [comment]
@barthalion Do you have an Idea why it is not working? I searched the documentation. To my understanding, it should work. Or are beta versions excluded?

**Comment by marbub** [comment]
@bbhtt or @Erick555 Do you know why it is not working?

**Comment by Erick555** [comment]
update bot works only for default (master) branch.

**Comment by marbub** [comment]
@Erick555 Is there any plan to support the beta brunch, too?

**Comment by bbhtt** [comment]
You can use a custom workflow to run on multiple branches https://github.com/flathub/io.qt.qtwebengine.BaseApp/blob/wiki/.github/workflows/update.yaml

Turn off the default one https://docs.flathub.org/docs/for-app-authors/external-data-checker#disable

**Comment by marbub** [comment]
I will think about it. Thank you for the help!
