### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by 4c0n** [flathub/io.qt.QtCreator#19]
Setting up android support is complicated. After installing the NDK/SDK and everything using Qt Creator, you still cannot use it, because there needs to be a Qt version that was compiled using it. This is causing a chicken and egg type problem.

In order to provide a turn-key solution and allow developers to start developing right after installation we should probably:
- Move the jdk installation module up
- Install the NDK/SDK using sdkmanager
- Preconfigure Qt Creator with the Qt version, device, kit, etc...

**Comment by 4c0n** [comment]
https://doc-snapshots.qt.io/qt6-dev/android-building.html

**Comment by 4c0n** [comment]
Once https://github.com/flathub/io.qt.QtCreator/tree/use-extension is merged we'll have support for extensions. Qt for android should become one of the extensions.

**Comment by marbub** [comment]
I think Android support is complicated. The Qt installer supports Android, so let's close it for now.
