### ISSUE TITLE
ClangFormat plugin doesn't load

### ISSUE THREAD

**Issue by qarkai** [flathub/io.qt.QtCreator#2]
Got error:

Disabling ClangFormat plugin as it has not been built against a modified Clang's libFormat.For more information see the Qt Creator README at https://code.qt.io/cgit/qt-creator/qt-creator.git/tree/README.md

**Comment by 4c0n** [comment]
Hi @qarkai,

Actually it is not an error, but more of a notice. The current flatpak version is not compiled with support for the ClangFormat plugin.
I am working on getting that working here: https://github.com/flathub/io.qt.QtCreator/pull/1 maybe you can test it?
The installation size is too big for my liking, but it should work.

**Comment by gasinvein** [comment]
The SDK extension `org.freedesktop.Sdk.Extension.llvm11` is built with `clang-tools-extra` enabled and I believe has all the needed `libclang*` libs. Can we use that instead of bundling llvm?

**Comment by 4c0n** [comment]
@gasinvein No unfortunately we can't. It has to be the fork because it contains patches specific to Qt Creator.

**Comment by 4c0n** [comment]
New version compiled with support for the plugin should be available to you in the next few hours.
https://github.com/flathub/io.qt.QtCreator/pull/1 solved the issue.

Enjoy! :smiley:
