### ISSUE TITLE
Add support of ssh-auth

### ISSUE THREAD

**Issue by oldkentuckymark** [flathub/io.qt.QtCreator#204]
ksshaskpass is not included with the environment, making git non functional.

![qtc](https://github.com/user-attachments/assets/6d903728-5bcd-4c66-9bc1-29e216b63447)

**Comment by marbub** [comment]
AFAIK Qt Creator has already kwallet support with a DBUS interface. I am not using a password manager for ssh but the public key system. So I never run into that problem.

Can you add the DBUS interface "org.kde.KWallet" with FlatSeal? If that works I will add that to the flatpak build file.

**Comment by marbub** [comment]
If you want ksshaskpass added to the kde runtime you have to file a bug report there. Everything under /usr is from the runtime.

**Comment by marbub** [comment]
To my understanding, KWallet supports org. freedesktop.portal.Secret. And Qt Creator is compiled with libsecrets(I never tested that).

**Comment by oldkentuckymark** [comment]
> AFAIK Qt Creator has already kwallet support with a DBUS interface. I am not using a password manager for ssh but the public key system. So I never run into that problem.
> 
> Can you add the DBUS interface "org.kde.KWallet" with FlatSeal? If that works I will add that to the flatpak build file.

I gave "org.kde.KWallet" talk permissions on both the session bus and system bus policy sections, no change.

**Comment by oldkentuckymark** [comment]
> If you want ksshaskpass added to the kde runtime you have to file a bug report there. Everything under /usr is from the runtime.

I'm an end user, I don't (and should not have to) know or care what a runtime is, or what comes in it, I know this application is supposed to be able to use git and it can not. If the password asking doohickey doesn't come with a runtime, then the app should ship it (doesn't matter to me weather it's in /usr or /app). Otherwise this flatpak is broken.

**Comment by marbub** [comment]
Like I said, most people use a public key for git. So it works. So you you changed the ssh-passkey executable back to the default?

**Comment by oldkentuckymark** [comment]
> Like I said, most people use a public key for git. So it works. So you you changed the ssh-passkey executable back to the default?

Other people use a password for git. and git officially supports that. So it does not work. This software says it supports git, by having a git menu. Shipping half functional and broken software like this is malpractice against users, because you have tricked them, and wasted their time. 

I just want git (ALL OF IT) to work in the program that has a git menu. It appears it does not work because this flatpak is not shipping everything it needs to come with to actually work as advertised, though I'm not an expert.

**Comment by marbub** [comment]
You can remove the setting in QtCreator. It should [call the ssh agent from the host system](https://invent.kde.org/plasma/ksshaskpass/-/issues/4).
