### ISSUE TITLE
third party plugins

### ISSUE THREAD

**Issue by christian-rauch** [flathub/io.qt.QtCreator#22]
Are you willing to add out-of-tree third-party plugins? I help to maintain https://github.com/ros-industrial/ros_qtc_plugin. Since there is no easy way to distribute third-party plugins, and this plugin needs the Qt Creator source tree to compile, it would be useful to distribute it as part of this flatpak.

**Comment by 4c0n** [comment]
Hi Christian,

Thanks for your interest in this project.
I'm not sure about adding a third party plugin to the flatpak. As it is right now, the build time is already quite long (at least 6 hours, usually around 8). And I'm working on turn key android support which requires building Qt all over again with different flags.

To be honest I feel it's getting a bit out of control already and am considering restructuring the whole thing using extensions or a dedicated runtime, but there isn't a lot of information/documentation on that.

Back to adding your plugin: do you think it would somehow be possible to make it available as a flatpak extension that people can choose to install it should they wish to?

**Comment by christian-rauch** [comment]
> As it is right now, the build time is already quite long

I saw that you build from source. Have you considered just using the binary package from the "official" distributed Qt Creator? This should definitely reduce the build time.

> do you think it would somehow be possible to make it available as a flatpak extension

I didn't know that there are "extensions". I always thought that a flatpak is one single "thing" that needs to provide everything. Do you have an example of how this can be done? If this makes things easier, I am happy to look into it.

**Comment by 4c0n** [comment]
Sure not compiling and linking anything would reduce the build time totally agree on that.

The extensions part is being discussed here for example: https://github.com/flathub/flathub/issues/1612

**Comment by bam80** [comment]
Was it actually completed, can we have a ref then?

**Comment by marbub** [comment]
Hi @christian-rauch , I took over ownership of the flatpak for QtCreator.

Are you still interested to get the plugin in? I am not sure what is the best approach. Qt Creator has no ABI. Do you have the plugin ready at launch time. Then we simply can add it.

**Comment by christian-rauch** [comment]
I would still be interested in general to distribute the plugin in a binary form, easily accessible for users.

However, due to the access restrictions of the flatpak sandbox, I am not sure how Qt Creator can access third-party development tools, SDKs and essentially run the build process outside of the flatpak with full access to the system dependencies. This is somehow possible, as demonstrated by `org.gnome.Builder`, but probably not easy to implement.

Unless the Qt Creator flatpak has a way to use system dependencies and programs outside of the flatpak, there is nothing we could gain from adding the plugin.

I am maintaining a "classic" snap that bundles Qt Creator with the plugin. Maintaining this as classic snap is a PITA, but it's the only way to distribute this such that it can access the system, without the need to write your own installer.

**Comment by marbub** [comment]
It can access the host, so only /usr etc. is not accessible. Actually, it is not so hard to implement complete host access. There is "flatpack-spawn --host," and we can mount /usr to a different mount inside the flatpack. Qt Creator would need a backend for Utils::FilePath.

But that is not the route I like to take. We have the flatpack SDK, which already provides many tools. The rest could be provided by Conan and Vcpkg, distributed by the Qt Creator flatpack. Or by SDKs in the home directory. Personally, I find a C++ package manager much more practical than the distribution package manager with its outdated packages.

I already use this flatpak for Qt development. The Qt I use comes from the SDK. That works without any problems.

**Comment by christian-rauch** [comment]
> There is "flatpack-spawn --host,"

Right. That's how Builder is solving this issue.

> But that is not the route I like to take. We have the flatpack SDK, which already provides many tools. The rest could be provided by Conan and Vcpkg, distributed by the Qt Creator flatpack.

Unfortunately, there is no single C/C++ (or generic) binary and source dependency tracker that would cover all packages that users potentially need. If all you need is Qt, then you are lucky. But otherwise, I think it's quite hard to provide a solution via an integrated package manager that covers all use cases.

**Comment by marbub** [comment]
> > There is "flatpack-spawn --host,"
> 
> Right. That's how Builder is solving this issue.

I am not sure because the packages from the distribution repository are often outdated. LTS distributions are still popular
 , but I found them unuseful. But it is a solution for some people.

> > But that is not the route I like to take. We have the flatpack SDK, which already provides many tools. The rest could be provided by Conan and Vcpkg, distributed by the Qt Creator flatpack.
> 
> Unfortunately, there is no single C/C++ (or generic) binary and source dependency tracker that would cover all packages that users potentially need. If all you need is Qt, then you are lucky. But otherwise, I think it's quite hard to provide a solution via an integrated package manager that covers all use cases.

I think there is no solution for everybody. In our project, we use submodules. We could use Conan, but it works, and nobody wants to change it.

The flatpak already provides an easy solution. Just install it and start. You don't have to install packages. It even installs PySide automatically if you add a Python project. I see there are other cases, but I am unsure how much the distribution packages are covering, that is not covered by Conan or Vcpkg.

**Comment by christian-rauch** [comment]
> I am not sure because the packages from the distribution repository are often outdated. LTS distributions are still popular, but I found them unuseful. But it is a solution for some people.

I would say that such decisions should not come down to personal preference but to user needs. At least in my field, system packages are often used since there is simply not a single packaging system that provides packages for everything. The Debian repos happen to have many pre-packaged libraries.

> The flatpak already provides an easy solution. Just install it and start. You don't have to install packages. It even installs PySide automatically if you add a Python project.

I don't understand what you mean by "Just install it and start. You don't have to install packages." when we are discussing the need for third-party dependencies here. You cannot simply build a project in a flatpak environment when its dependencies are not satisfied by whatever SDK you provide with the flatpak.

> I see there are other cases, but I am unsure how much the distribution packages are covering, that is not covered by Conan or Vcpkg.

vcpkg does not distribute packages as binaries; you have to compile everything from scratch. And then, there are packages that are simply not provided by the two package managers / repos.

We are going around in circles here. If you are personally fine with this setting because your own projects either only depend on the Qt SDK or build their dependencies from scratch, that is fine with me. But you have to accept that there are users that use "external" package managers.

Maybe the only way around this issue is to run the build process in a dev container (Docker container) where projects can use whatever package manager to satisfy their dependencies.

**Comment by marbub** [comment]
> > I am not sure because the packages from the distribution repository are often outdated. LTS distributions are still popular, but I found them unuseful. But it is a solution for some people.
> 
> I would say that such decisions should not come down to personal preference but to user needs. At least in my field, system packages are often used since there is simply not a single packaging system that provides packages for everything. The Debian repos happen to have many pre-packaged libraries.

I think we aim for different goals. Flatpak will not satisfy all people, but it can work for many, so it is one option. Snap, for example, works for people on Ubuntu. AppImage is even hit-and-miss, etc. I work in an environment where people work on different operating systems. When we onboard people, it takes some days because they use different environments. 

> > The flatpak already provides an easy solution. Just install it and start. You don't have to install packages. It even installs PySide automatically if you add a Python project.
> 
> I don't understand what you mean by "Just install it and start. You don't have to install packages." when we are discussing the need for third-party dependencies here. You cannot simply build a project in a flatpak environment when its dependencies are not satisfied by whatever SDK you provide with the flatpak.

Okay, my aim is that there is a recipe for Conan or Vcpkg in the project, and people can just start, similar to pip in Python. I hope that is more clear.

> > I see there are other cases, but I am unsure how much the distribution packages are covering, that is not covered by Conan or Vcpkg.
> 
> vcpkg does not distribute packages as binaries; you have to compile everything from scratch. And then, there are packages that are simply not provided by the two package managers / repos.

Yes, but is that an argument against distributing Qt Creator as Flatpak? There are even other ways to provide dependencies. An SDK can be installed in your home directory. That is really common and works for me with Flatpak. Many projects provide dependencies as submodules.

> We are going around in circles here. If you are personally fine with this setting because your own projects either only depend on the Qt SDK or build their dependencies from scratch, that is fine with me. But you have to accept that there are users that use "external" package managers.

Yes, and I accept that. So the flatpak is not for them. My argument is that there is a solution for many. And my aim is to provide an automatic solution.
 
> Maybe the only way around this issue is to run the build process in a dev container (Docker container) where projects can use whatever package manager to satisfy their dependencies.

I use(d) Distrobox for some of my applications. It is based on Podman or Docker. Yes, it is working. Yes, containers are a solution for some projects. However, if support for different operating systems is needed, it will not work. As I said, there is simply no solution that will work for everybody. 

Flatpak is one solution. It provides a uniform environment. I see that you prefer different solutions. If you don't want to use this distribution channel anymore, I would say, we can stop the discussion. ;-)

**Comment by christian-rauch** [comment]
> Yes, but is that an argument against distributing Qt Creator as Flatpak? There are even other ways to provide dependencies. An SDK can be installed in your home directory. That is really common and works for me with Flatpak. Many projects provide dependencies as submodules.

No. If the Qt Creator flatpak work for your use case, then this is completely fine. I am just mentioning the issue with system access since the plugin that I have in mind is using third-party tools outside the flatpak and most projects it builds also rely on system dependencies. Therefore, if the Qt Creator flatpak cannot access the system, e.g. via [`flatpak-spawn --host`](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn), then this plugin cannot work and adding it to the flatpak does not make sense.

I am not arguing against the Qt Creator flatpak, I am arguing against adding the plugin unless it can run commands on the host outside the flatpak.

**Comment by marbub** [comment]
> > Yes, but is that an argument against distributing Qt Creator as Flatpak? There are even other ways to provide dependencies. An SDK can be installed in your home directory. That is really common and works for me with Flatpak. Many projects provide dependencies as submodules.
> 
> No. If the Qt Creator flatpak work for your use case, then this is completely fine. I am just mentioning the issue with system access since the plugin that I have in mind is using third-party tools outside the flatpak and most projects it builds also rely on system dependencies. 

What are these third-party tools? I'd like to add some more useful tools. I added mold because I use TDD, and a fast linker is a big bonus. Maybe some are of general interest. I was thinking of adding Docker and Podman, but it seems not be easy: https://github.com/flathub/com.visualstudio.code/issues/55 And I don't use it myself. So the testing would be not there.

> Therefore, if the Qt Creator flatpak cannot access the system, e.g. via [`flatpak-spawn --host`](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn), then this plugin cannot work and adding it to the flatpak does not make sense.

Yeah, it would be nice. But the QtCreator team has no user story for it, and I won't be able to do it in my free time. 
 
> I am not arguing against the Qt Creator flatpak, I am arguing against adding the plugin unless it can run commands on the host outside the flatpak.

I understand your point, but I am not in your context. I only tried to understand what are the concrete dependencies.

**Comment by christian-rauch** [comment]
> What are these third-party tools? I'd like to add some more useful tools.

These would be [colcon](https://colcon.readthedocs.io/en/released/index.html) and [catkin_tools](https://catkin-tools.readthedocs.io/en/latest/) with all their possibly third-party plugins.

However, I am, and probably a lot of users of the ROS plugin, are going to use colcon and catkin_tools to actually build workspaces with ROS packages that depend on many system packages. So even with those tools in the flatpak, the usage of the ROS plugin would be very limited.

**Comment by marbub** [comment]
> > What are these third-party tools? I'd like to add some more useful tools.
> 
> These would be [colcon](https://colcon.readthedocs.io/en/released/index.html) and [catkin_tools](https://catkin-tools.readthedocs.io/en/latest/) with all their possibly third-party plugins.

If I understand it right, these are meta tools. flatoak-spawn is maybe the best way for them. 

> However, I am, and probably a lot of users of the ROS plugin, are going to use colcon and catkin_tools to actually build workspaces with ROS packages that depend on many system packages. So even with those tools in the flatpak, the usage of the ROS plugin would be very limited.

Yes, maybe you are right and the easiest path forward would be a container like Docker/Podman. If I find time, I will look into it.

**Comment by christian-rauch** [comment]
> If I understand it right, these are meta tools. flatoak-spawn is maybe the best way for them.

Right. I could potentially write a wrapper around them. But it would still be impossible to introspect the dependencies for code completion etc. in Qt Creator. So I don't see much value in this. I guess people would simply not use it and prefer a Qt Creator distribution that has access to the host dependencies.

**Comment by marbub** [comment]
> > If I understand it right, these are meta tools. flatoak-spawn is maybe the best way for them.
> 
> Right. I could potentially write a wrapper around them. But it would still be impossible to introspect the dependencies for code completion etc. in Qt Creator. So I don't see much value in this. I guess people would simply not use it and prefer a Qt Creator distribution that has access to the host dependencies.

To my understanding, QtCreator should handle that for you if you use their API. It should be handled by FilePath. You actually have access to the hosts '/usr' and '/etc/' by using the special options host-os and host-etc in Flatpak. It would be mapped to a different directory, but FilePath should hide the fact by providing a backend.

**Comment by bam80** [comment]
> I was thinking of adding Docker and Podman, but it seems not be easy: [flathub/com.visualstudio.code#55](https://github.com/flathub/com.visualstudio.code/issues/55)

It seems like flatpak-spawn is a way to go there, could add it here, too?

Also, this conversation apparently has not been finished yet, shall we reopen, please?

**Comment by marbub** [comment]
Yes, there is an abstraction in Qt Creator for it but somebody has to add it to Qt Creator.

**Comment by bam80** [comment]
What do you mean? flatpak-spawn seems unrelated to any Qt Creator abstractions.

**Comment by marbub** [comment]
Qt Creator needs to use flatpak-spawn. It needs to read the host file system too. You already can do that today with ssh. So you could ssh into your container.

**Comment by bam80** [comment]
If you read https://github.com/flathub/com.visualstudio.code/issues/55 carefully, VS Code has nothing to do with flatpak-spawn. Neither does Qt Creator.
flatpak-spawn just needs to be included in the flatpak here.

**Comment by marbub** [comment]
But that is about podman and docker.

**Comment by bam80** [comment]
Yes, hosts' podman and docker would able to be called from within the flatpak then. No low level integration with Qt Creator is needed:
https://github.com/flathub/com.visualstudio.code/issues/55#issuecomment-2504507900
```
mkdir -p ${HOME}/.var/app/com.visualstudio.code/data/node_modules/bin
ln -sf /app/bin/host-spawn ${HOME}/.var/app/com.visualstudio.code/data/node_modules/bin/podman
```

**Comment by marbub** [comment]
I spoke with the principal developer of Qt Creator and his advice was to add Flatpak support into Utils::File path.

**Comment by bam80** [comment]
That's fine, but until it's happened, adding flatpak-spawn is easy and would solve the major problem I think.

**Comment by marbub** [comment]
I can review your merge request.
