### ISSUE TITLE
flatpak too large?

### ISSUE THREAD

**Issue by christian-rauch** [flathub/io.qt.QtCreator#23]
When I install the flatpak via `flatpak install flathub io.qt.QtCreator`, it downloads a 5.8GB package.

That is quite large compared to the binary distribution which is less than 1GB. Is this expected? Does the flatpak contain optional files, such as debug symbols etc.?

**Comment by 4c0n** [comment]
Hi Christian,

Qt6 is also bundled for example. If you think you can optimize the size by using different build flags, then of course by my guest.
In any case you can always have a look at the manifest to get a good idea of what's inside.
Also you can run `flatpak run --command=sh io.qt.QtCreator` to inspect things from the inside.

**Comment by christian-rauch** [comment]
Installed, it is actually 14GB:
```
[📦 io.qt.QtCreator app]$ du -h -d 1
270M	./jmods
22M	./share
14M	./translations
320K	./phrasebooks
231M	./qml
44M	./include
3.1M	./mkspecs
2.7G	./bin
156K	./conf
367M	./plugins
8.8G	./lib
952M	./examples
267M	./libexec
336M	./doc
356K	./modules
14G	.
```

One reason is that some libraries are really huge compared to the ones shipped in the "official" binary distribution. E.g., `libclang.so.11` in the flatpak:
```
[📦 io.qt.QtCreator app]$ ls -alh lib/libclang.so.11
-rwxr-xr-x 2 nfsnobody nfsnobody 1.2G Jan  1  1970 lib/libclang.so.11
```
is 1.2GB (possibly because of debug information), while in the binary distribution:
```
christian@gungnir:~$ ls -alh $HOME/Qt/Tools/QtCreator/lib/qtcreator/libclang.so.11
-rwxr-xr-x 1 christian christian 49M Jun  8 12:25 /home/christian/Qt/Tools/QtCreator/lib/qtcreator/libclang.so.11
```
this is only 49MB.

Is Qt6 required to build/run Qt Creator or is this really just to provide the development libraries for compiling projects that use Qt? Because to use Qt as runtime, you could just use the KDE flatpak runtime, and for development, you could just use the libraries from the host system (either system installed or manually by the user, e.g. through the binary distribution).

**Comment by 4c0n** [comment]
@christian-rauch I'm not really sure where your going with all of this. Are you in need of disk space?

**Comment by christian-rauch** [comment]
Actually yes, I had to uninstall the flatpak again as I only had less than 1GB space left after installing it. I was just wondering if the large size was intended to provide dependencies etc. or if this is an oversight.

**Comment by christian-rauch** [comment]
Would you be interested in replacing the current "compile-from-source" manifest with one that simply uses the binary distribution of Qt Creator? That would mean that the manifest would only download the archives with the binary distribution from the official repo. This reduces the flatpak size and the time to create it. Using the official binaries also gives you the benefit of being compatible to binary distributed plugins.

**Comment by 4c0n** [comment]
@christian-rauch No, I am not interested in that. I would be interested in seeing the size reduced by optimizing the build(s). If you're interested you can try that and open a PR, which I will gladly review.

**Comment by simonschmeisser** [comment]
It should be possible to strip debug information from some libs to reduce the size, anything that is used internally only. The `libclang` you mentioned sounds like a good candidate

**Comment by 4c0n** [comment]
Feel free to give that a try and open a PR @simonschmeisser
