### ISSUE TITLE
Important Python modules are missing

### ISSUE THREAD

**Issue by zocker-160** [flathub/io.qt.QtCreator#31]
When creating a new Qt-Quick for Python project and pressing "run", I get the following error:

```
Traceback (most recent call last):
  File "/home/zocker/Programmierkram/IDEs/QtCreator/untitled/main.py", line 6, in <module>
    from PySide6.QtGui import QGuiApplication
ModuleNotFoundError: No module named 'PySide6'
```

Without that, creating a Python application is impossible, can I somehow install those modules into the Flatpak or use the ones installed on my system?

**Comment by 4c0n** [comment]
When https://github.com/flathub/io.qt.QtCreator/tree/use-extension is merged, it will be possible to use app extensions.
I plan on adding extensions for the Python bindings for Qt5 and for Qt6.

**Comment by zocker-160** [comment]
nice, thank you for your effort!

**Comment by marbub** [comment]
I spoke with the PySide developers and we have a plan to support the Qt Creator flatpak. We want to add an extension.

**Comment by bbhtt** [comment]
Without an extension point in the org.kde.Sdk, you cannot build Qt modules as extensions. These extensions come from `org.freedesktop.Sdk` which does not have Qt, only `org.kde.Sdk` has it. 

Pyside6/QtWebengine etc. requires rest of the Qt modules at build time and runtime (which are in the KDE SDK).

KDE runtime has only a few extension points for themes https://invent.kde.org/packaging/flatpak-kde-runtime/-/blob/56923a59b894867d98d38856b76ddecc3254197e/org.kde.Sdk.json.in#L30-64

eg. https://github.com/flathub/org.kde.WaylandDecoration.QAdwaitaDecorations

I spoke with KDE last year, they aren't interested in having pyside6 because nothing in the KDE stack uses it. The long term plan for Qtwebengine (for me) is to move it to the runtime directly. Currently too many issues and API/ABI issues happen when it is detached.

**Comment by bbhtt** [comment]
Pyside6 is also PITA to maintain and needs one patch or two every release. If you want to build it from source see https://github.com/flathub/io.github.hydrusnetwork.hydrus/blob/c19447fcd70e391c5b0794ba47bbdfd8c9b8e567/io.github.hydrusnetwork.hydrus.yml#L250-L289 which I maintain.

See https://github.com/flathub/org.freecadweb.FreeCAD/blob/105074876d9b26ab0469d6b68589faeeff2fd59a/org.freecadweb.FreeCAD.yaml#L35 for pyside2

**Comment by marbub** [comment]
I found out that the KDE runtime does not provide many Qt modules. It seems that the KDE runtime is not a full Qt runtime. :-/

The idea was to create an application extension point, but I am not sure if that can be shared between different applications.

**Comment by 4c0n** [comment]
Ah you have now reached the same conclusion as I have about the kde SDK/runtime.
Others and myself have tried starting a conversation about this, but have unfortunately gotten nowhere, this is the main reason I have given up on maintaining this flatpak and is the reason it was set up the way that it was.

My honest opinion is that it would be much better if the kde runtime would be based on a modular setup, having Qt available as extensions, that way the KDE runtime could be made up using what they need and it would be possible to use them in the vanilla SDK as well, thus providing a means to provide a flatpak for any application that uses modules that the KDE runtime does not provide. Qt creator would be a prime example of that.

Some members of the flathub community however spoke out negatively on that idea as did the KDE people (they basically did not have any need for it and would not benefit from the added complexity directly themselves), while flathub/freedesktop maintainers never even responded at all. Which in my honest opinion is a real shame.

There does not seem to be a good solution going forward if on one hand the resources it takes to build it ourselves are too much and on the other hand it is not possible to discuss or get any cooperation on the/an alternative...

**Comment by marbub** [comment]
I am making a new package. 

Now you can type:

pip install PySide6

in the terminal in QtCreator. I hope that is good enough for you.

**Comment by zocker-160** [comment]
thank you :heart:

**Comment by marbub** [comment]
I didn't check if PySide works after Pip installs it. If you find any problems, please reopen the bug report.
