### ISSUE TITLE
Host's toolchain support?

### ISSUE THREAD

**Issue by bam80** [flathub/io.qt.QtCreator#45]
Hi, thanks for this.

Does it have access to host's toolchains/SDKs?
If not, could we use portals for that maybe?

Otherwise, in this form, QtCreator is not very useful, IMO..

**Comment by 4c0n** [comment]
Hi @bam80, you're welcome.

The flatpak does not have access to the host's toolchains/SDKs.
It does come with Qt5 and Qt6 and is meant to provide a turn-key solution to get started with Qt. Could you specify what exactly it is that you're missing and need access to on your host system?

Thanks for sharing you're opinion...

**Comment by bam80** [comment]
I have self-built Qt and also special scross-toolchain I need to work with.

**Comment by 4c0n** [comment]
That sounds like a very specific use case. I guess you would be better of using a different solution at this point in time.
If you feel differently, please provide some use cases in which this would be useful to the general public and open a pull request with your suggested solution.

**Comment by bam80** [comment]
My requirements are actually rather typical for a real-world development.
About the solution, that is what I would like to know for myself :)

One of the "solutions" is to get it unrestricted access, I guess..
