### ISSUE TITLE
Flatpak update fails

### ISSUE THREAD

**Issue by infra-monkey** [flathub/io.qt.QtCreator#47]
Hello,

I reported the same issue a few weeks ago. Flatpak artifact doesn't seem available when doing an update:

Here is the output:
flatpak update 
Looking for updates…

        ID                      Branch         Op         Remote          Download
 1. [✗] io.qt.QtCreator         stable         u          flathub         1.0 kB / 6.2 GB

Error: Error pulling from repo: While pulling app/io.qt.QtCreator/x86_64/stable from remote flathub: fsck f51436ce394546800a3dc51a21b61e9c2f82877ce8e7bc057616c68c6ec1f94e.dirtree: No such metadata object f51436ce394546800a3dc51a21b61e9c2f82877ce8e7bc057616c68c6ec1f94e.dirtree
Updates complete.
error: There were one or more errors

Uninstall/install however works.

**Comment by 4c0n** [comment]
I posted it here: https://discourse.flathub.org/t/updates-fail-but-reinstalling-works/1996
Hopefully someone will have a look at it and respond to it soon.

**Comment by hfiguiere** [comment]
try `flatpak repair`
