### ISSUE TITLE
Flatpak version seems to be incapable finding host system libraries

### ISSUE THREAD

**Issue by ph1234567890** [flathub/io.qt.QtCreator#53]
Running it on Ubuntu 21.10
Cannot seem to get flatpak-ed QtCreator to find libraries installed on the machine.
Specifically, `find_package(Boost ...)` always fails, while working fine if run directly via cmake.
Also tried installing QtCreator in a dpkg via aptitude. No problem finding local libraries at all (though the version is a lot older than that in flatpak).

I have granted io.qt.QtCreator `device=all`, syscalls `allow=devel`, `filesystem=host`, `filesystem=host-os`, `filesystem=host-etc`, `filesystem=home`. Also explicitly added `/usr` and `/lib` to the permitted folders.

Is there anything I am missing? (Ability to find local libraries seems pretty important for an IDE)

**Comment by 4c0n** [comment]
The flatpak runs in a sandbox, so when you run cmake inside the sandbox it will not find the libs on your host.
I think what you'd want to do in this case is run cmake on the host using `flatpak-spawn`. That'll require some configuration of Qt Creator though.

Allowing the flatpak access to `/usr` and `/lib` might be possible however I'm not sure where they end up in the sandbox, it would most likely not be `/usr` and `/lib` as the sandbox already occupies those locations, but if you can find out where they are, you could use a cmake flag to tell cmake where to look. However it would probably cause issues with linking as in the end the libs are probably linked against libs in once again another location at that point. Also the cmake config files for the libs might have absolute paths... So the first option seems more feasible.

**Comment by alaricmahmud22** [comment]
How should you go about configuring QtCreator with `flatpak-spawn` ?
Perhaps you could direct me to some documentation please

**Comment by 4c0n** [comment]
https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn
https://doc.qt.io/qtcreator/creator-project-cmake.html
