### ISSUE TITLE
Restore Qt Location module

### ISSUE THREAD

**Issue by 4c0n** [flathub/io.qt.QtCreator#56]
There is no 6.2.3 version of the Qt Location module and 6.2.1 does not seem compatible with the 6.2.3 version of the other modules.
It seems to be fixed in 6.3, but it's not released yet. So when it is we should try to restore the module as for it's not included.

**Comment by 4c0n** [comment]
There was no 6.3.0 release of the module. Hopefully it will get there next time around.

**Comment by marbub** [comment]
I think that is out of scope.
