### ISSUE TITLE
Decrease build times

### ISSUE THREAD

**Issue by 4c0n** [flathub/io.qt.QtCreator#61]
As mentioned in https://github.com/flathub/io.qt.QtCreator/pull/60, there is a strong desire to reduce the build time of this package.

Currently the build time is huge compared to most other packages. The main reasons for that are:
- QtCreator requires a patched version of clang which takes a long time to build
- We're building Qt6 from scratch on every change (this package uses the Qt5 LTS Sdk as a platform and packages Qt6 so that it can provide a turn key solution for maintaining existing apps and for developing new ones)

Suggestions that have come up so far are:
- Create a base app that includes the patched clang build and Qt6
- Create an Sdk extension for Qt6 (which could perhaps also be used in the KDE Sdk, that way Qt6 is a lot more reusable not just for this package but also for packages that require both GNOME and Qt or package builds that require multiple Qt versions)
- Use prebuilt versions of for example the patched clang and/or Qt6

**Comment by 4c0n** [comment]
> > (this package uses the Qt5 LTS Sdk as a platform
> 
> Note that you use abandoned 5.15 Sdk while currently supported one is 5.15-21.08
> 
> Maybe it would be better to use 6.2 Sdk and build qt5 LTS manually?

I'd rather stick with an LTS as base and build the newer packages. Eventually it will have to be swapped around though because Qt6 will become the new LTS, however I think it'll take a while. Upgrading to the newer LTS Sdk is a good idea though.

**Comment by christian-rauch** [comment]
That sounds reasonable.

I would also suggest using the SDK that already contains the Qt version you want to use. You can dramatically reduce the build time by [using an SDK that already ships Qt 6.2](https://github.com/christianrauch/flathub/blob/org.qtproject.qtcreator/org.qt_project.qtcreator.yaml). The point of LTS SDKs is usually stability within a Qt major version. But this makes only sense if your application actually uses the Qt version of that SDK. In the case of Qt Creator, which now requires Qt 6.2 and cannot be built with Qt 5.15, relying on the LTS SDK does not provide benefits. At least I don't see the point of relying on a long-term supported Qt 5.15, when it is not used as runtime for the application.

Additionally, I would suggest to use the "official" binaries that are distributed by the Qt and Qt Creator installer whenever possible. For amd64, you can use the official binaries from https://download.qt.io/official_releases/qtcreator/ for Qt, Qt Creator and all its dependencies. We do this in the CI builds for https://github.com/ros-industrial/ros_qtc_plugin already to save build time. I proposed that a while ago https://github.com/flathub/io.qt.QtCreator/issues/23#issuecomment-914562816 but this suggestion was not well received. Would you maybe now consider the "official" binary distributions instead of building everything from source?

**Comment by Erick555** [comment]
Note that if you decide to make qt extension then you shouldn't build qtcreator against qt from extension as it would make the extension a hard dependency thus defeat the point of extension. qtcreator needs to be build against qt from runtime i.e. 6.2 and then qt5 could be made as optional extension.

**Comment by 4c0n** [comment]
> Note that if you decide to make qt extension then you shouldn't build qtcreator against qt from extension as it would make the extension a hard dependency thus defeat the point of extension. qtcreator needs to be build against qt from runtime i.e. 6.2 and then qt5 could be made as optional extension.

Yeah it does need to keep Qt6 or be build with Qt5, there are some issues however. The kde Sdk has about 15 modules missing and does not include examples. I've considered just putting the missing packages in the extension, but that poses the problem of keeping it exactly in sync with the Sdk versions of Qt in the Sdk. So I'd have to manually check that every time an update is available (and I don't want to deal with that).

What I was thinking at first was to make Sdk extensions for both Qt5 and Qt6 and making app extensions using the Sdk extensions, however as you pointed out there's a hard dependency on the one that Qt Creator is built with, so that one cannot be optional. So I guess making an app extension for that one is pointless, however we still need the docs + examples, but I guess that can become part of the base app or the app itself. In any case I noticed that because the runtime is an Sdk the sdk extensions stay available when running the app as well, so that's how it can be there.

> Another thing is app extension can live only somewhere under /app not /usr.
That's not such a big deal, it's currently the case and the locations can be configured automatically using Qt Creator sdktool.

**Comment by 4c0n** [comment]
Work in progress here:

- https://github.com/flathub/io.qt.QtCreator/tree/use-extension
- https://github.com/flathub/flathub/pull/3014
- https://github.com/flathub/flathub/pull/3013
- https://github.com/flathub/flathub/pull/3012

Currently using Qt6 from new Sdk extension (mandatory), Qt5 from app extension (uninstallable/optional).

**Comment by Erick555** [comment]
I would advice to make `io.qt.QtCreator.Extension.Qt5/6` app extensions. Their usefulness is pretty contained to QtCreator app.

**Comment by 4c0n** [comment]
It really isn't just useful for Qt Creator, the Sdk extensions are useful for anyone that needs the (full) Qt framework and not just the parts that KDE uses.

**Comment by Erick555** [comment]
Examples please.

**Comment by 4c0n** [comment]
It seems like there would be many, even the Qt dev states it here: https://github.com/flathub/io.qt.QtCreator/pull/60#issuecomment-1077859521

**Comment by Erick555** [comment]
I repeat KDE runtime has GKT already. Did you check what's included in flatpak runtimes?

**Comment by christian-rauch** [comment]
@4c0n This is great. Thanks for the work.

> I repeat KDE runtime has GtK already. Did you check what's included in flatpak runtimes? This is why I have such concerns with your proposals - I think you may not be aware of many flatpak/flathub/runtimes details.

@Erick555 I don't think the KDE SDK provides a full GTK stack, in the same way that the Gnome SDK does not provide Qt. Can you give an example and point to the definitions of the runtimes, where they include both toolkits? In any case, this will still prevent you from using multiple toolkits in one flatpak, unless you install all of them manually.

> I would advise to make io.qt.QtCreator.Extension.Qt5/6 app extensions only. Their usefulness is pretty contained to QtCreator app.

@Erick555 As far as I understand this, `org.freedesktop.Sdk.Extension.qt6` can be used by any IDE, e.g. `org.gnome.Builder` and `com.visualstudio.code`. Why do you think these SDK extensions cannot be used outside of Qt Creator?

**Comment by Erick555** [comment]
GTK is included in [freedesktop-sdk](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/components/gtk3.bst) which is included in KDE runtime. Freedesktop-sdk is used by gtk apps that don't have gnome specific dependencies (at least not much of them) like firefox or libreoffice. It's true that freedesktop-sdk and KDE runtimes don't contain broad variety of gnome tools but which exact app would need those? Which app does build Qt while using gnome runtime right now?

> As far as I understand this, org.freedesktop.Sdk.Extension.qt6 can be used by any IDE, e.g. org.gnome.Builder and com.visualstudio.code. Why do you think these SDK extensions cannot be used outside of Qt Creator?

I didn't saw maintainers of those requesting Qt extension. In fact users may not need Qt provided in flatpak form as they can get it themselves like they would do outside flatpak. This was even [suggested](https://github.com/flathub/io.qt.QtCreator/pull/60#issuecomment-1078343378) by upstream Qt developer. Someoje even proposed [fork](https://github.com/flathub/flathub/pull/2712) of QtCreator flatpak with same approach. It's only personal preference of current QtCreator maintainer to insist on shipping every possible thing user may want alongside main flatpak app. No other IDE shares this approach.

**Comment by Erick555** [comment]
Something like below would work:

QtCreator build against Qt6 runtime (note that runtime doesn't even contain any KDE components which is at odds with the claim that KDE runtimes are for KDE apps.)

Separate `io.qt.QtCreator.Extension.Qt5` and` io.qt.QtCreator.Extension.Qt6` extensions. Users may download any of them or none at all if they don't need. The app itself wouldn't depend on them. That will solve build-time and size issues and you could maintain those extensions as you wish.

**Comment by christian-rauch** [comment]
@Erick555 Why are you so focused on restricting the Qt SDK to Qt Creator? Why shouldn't it be possible for other IDEs to use the Qt SDKs?
Because of the sandbox, using SDKs outside the flatpak is not trivial. You have to run `flatpak-spawn` to start a process (e.g. a shell) that can access files outside the sandbox.

**Comment by Erick555** [comment]
Because conclusion from many discussions before was that separate Qt outside KDE runtime was unnecessary especially if it's going to be maintained by third party person with no affiliation to Qt or KDE. Did you asked yourself why there is no generic Qt extension or baseapp to date? Because the idea was rejected.

Apps with `filesystem=host` have access to most host files without flatpak-spawn.

**Comment by 4c0n** [comment]
If there were many discussions in the past about that, then wouldn't that indicate that there's a certain demand for it?
I'm sure before toilet paper was readily available people were also convinced that they didn't have a need for it, pardon the analogy here.
Anyway we'll see what happens I suppose, I wouldn't want to not try something because it might not have made sense in the past. Things change and this might be one of them.

Although the filesystem flag can provide limited access to the host filesystem, it doesn't provide access to the paths that would commonly hold the Qt installation as those paths are blacklisted https://docs.flatpak.org/en/latest/sandbox-permissions.html

and for example when running fedora silverblue or kinoite it wouldn't make much sense as you'd want to do development inside some sort of sandbox/container which is exactly what flatpak provides on those distros.

**Comment by Erick555** [comment]
I would just ask first before submitting anything.

There is `--filesystem=host-os` that give you everything inside `/run/host` in container but I was mostly thinking about using home or any path where users can store development files freely, i.e. downloading relevant Qt version from upstream and adding it as a kit from QtCreator interface.

**Comment by 4c0n** [comment]
Right, thanks for sharing your opinion. The idea is to provide a turn key solution for people to be able to easily get started with Qt development. What you're describing is something else, which is also already possible on top of it.

**Comment by marbub** [comment]
Build times are now much lower because the SDK is used.
