### ISSUE TITLE
QTest: No such file or directory

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/io.qt.QtCreator#72]
Including QTest fails for Qt5 and Qt6 configurations. Other headers, like QDebug or QUrl can be included without a problem.

An example project is attached.

[DesktopSchemeHelperTest.tar.gz](https://github.com/flathub/io.qt.QtCreator/files/9524205/DesktopSchemeHelperTest.tar.gz)

**Comment by Alexander-Wilms** [comment]
Not sure. Maybe one could check in Qt Creator installed from the distro repository where the file is supposed to be and check the path in the Flatpak.

**Comment by marbub** [comment]
Is that still a problem?

**Comment by Alexander-Wilms** [comment]
Yes, I just opened the project attached above, used the default config and got the same error:

![image](https://github.com/flathub/io.qt.QtCreator/assets/3226457/d6c87eaa-b5ac-4d66-bec5-69a284f8244f)

**Comment by marbub** [comment]
I haven't used qmake for some time, but how does it work if you don't add the qt test module to the project file?

**Comment by Alexander-Wilms** [comment]
Thanks, that was the solution. I added `QT += testlib` to the .pro file and now `#include <QTest>` works.
